### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by grokgrok** [ColdHeat/mech#19]
I guess this doesn't work with VMWare Desktop on Windows.....

```
c:>\temp>mech init https://atlas.hashicorp.com/bento/boxes/debian-8.6/versions/2.3.0/providers/vmware_desktop.box --name=bento
Initializing mech
vmware_desktop.box[################################] 464249/464249 - 00:06:19
Extracting...
What username would you like to save? [mech] vagrant
Saving C:\Users\baba/.mech\bento\mechfile
Finished.
Saving .\mechfile
Finished.

c:\temp>mech up bento
Traceback (most recent call last):
  File "c:\users\baba\appdata\local\enthought\canopy\user\scripts\mech-script.py", line 11, in <module>
    load_entry_point('mech==0.5', 'console_scripts', 'mech')()
  File "C:\Users\baba\AppData\Local\Enthought\Canopy\User\lib\site-packages\mech\__main__.py", line 111, in main
    operation(op='start', name=name, options={'gui':gui})
  File "C:\Users\baba\AppData\Local\Enthought\Canopy\User\lib\site-packages\mech\__main__.py", line 53, in operation
    method()
  File "C:\Users\baba\AppData\Local\Enthought\Canopy\User\lib\site-packages\mech\mech.py", line 63, in start
    vm.start()
  File "C:\Users\baba\AppData\Local\Enthought\Canopy\User\lib\site-packages\mech\vmrun.py", line 105, in start
    return self.vmrun( 'start', 'nogui' )
  File "C:\Users\baba\AppData\Local\Enthought\Canopy\User\lib\site-packages\mech\vmrun.py", line 46, in vmrun
    output = self.execute( self.VMRUN_PATH, *cmd )
  File "C:\Users\baba\AppData\Local\Enthought\Canopy\User\lib\site-packages\mech\vmrun.py", line 41, in execute
    p = subprocess.Popen( cmd, stdout=subprocess.PIPE )
  File "C:\Users\baba\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Users\baba\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by ColdHeat** [comment]
I've tested it to work on VMWare Workstation, are you using Player?

**Comment by grokgrok** [comment]
Yes. Is that the issue?

**Comment by ColdHeat** [comment]
VMware Player doesn't have the vmrun binary which is required for mech to work.

**Comment by ColdHeat** [comment]
You'll need to be using VMWare Workstation on Windows, there's unfortunately not a way around it.

**Comment by grokgrok** [comment]
k thx.
